### ISSUE TITLE
add config examples?

### ISSUE THREAD

**Issue by meinharrd** [pooleja/microtrxchannels#1]
hi james,

i am currently reverse engineering the config. i figured out that config/rpc.js should look something like this:

```
module.exports = {
  protocol: 'http',
  user: 'user',
  pass: 'pass',
  host: '127.0.0.1',
  port: '18332'
}
```

config/config.js like this:

```
module.exports = {
  NETWORK: {
    P2SHVersion: '5'
  }
}
```

maybe it would make sense to include empty or example config files?

**Comment by pooleja** [comment]
Yep, done.  I missed the template files I meant to check in.

**Comment by meinharrd** [comment]
perfect, thanks! :)
